server:
  port: '8083'
spring:
  application:
    name: 'product-catalog'
  data:
    mongodb:
      auto-index-creation: true
  mongodb:
    uri: 'mongodb://root:algashop@localhost:27017/product_catalog?authSource=admin'
logging:
  level:
    org.mongodb.driver.protocol.command: DEBUG
    org.mongodb.driver.protocol.query: DEBUG
    org.mongodb.driver.connection: DEBUG
algashop:
  data-load:
    enabled: false
    auto-drop: false
    sources:
      - location: db/testdata/categories.json
        collection: categories
      - location: db/testdata/products-large.json
        collection: products